#!/bin/bash -l
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -p debug
#SBATCH -t 00:10:00
#SBATCH -J ray-density
#SBATCH -o %j-ray-density.o
#SBATCH -e %j-ray-density.e

#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=16

conda activate nums

# Getting the node names
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)


# Start head node.
port=6379
ip_head=$head_node_ip:$port
export ip_head
echo "IP Head: $ip_head"

echo "Starting HEAD at $head_node"
srun --nodes=1 --ntasks=1 -w "$head_node" \
    ray start --head --node-ip-address="$head_node_ip" --port=$port \
    --num-cpus "${SLURM_CPUS_PER_TASK}" --block &

sleep 5

export MKL_NUM_THREADS=1
python -u ./test_density.py --address $ip_head
